version: "3.3"

networks:
  frontend:
  backend:

volumes:
  pgdata:
  opdata:


services:
  db:
    image: postgres:10
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: openproject
    networks:
      - backend

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - backend

  proxy:
    image: openproject/community:${TAG:-11}
    restart: unless-stopped
    command: "./docker/prod/proxy"
    ports:
      - "${PORT:-8080}:80"
    environment:
      APP_HOST: web
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    depends_on:
      - web
    networks:
      - frontend

  web:
    image: openproject/community:${TAG:-11}
    restart: unless-stopped
    environment:
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: 4
      RAILS_MAX_THREADS: 16
      USE_PUMA: "true"
      # set to true to enable the email receiving feature. See ./docker/cron for more options
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "opdata:/var/openproject/assets"
    command: "./docker/prod/web"
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
      - seeder

  worker:
    image: openproject/community:${TAG:-11}
    restart: unless-stopped
    environment:
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: 4
      RAILS_MAX_THREADS: 16
      USE_PUMA: "true"
      # set to true to enable the email receiving feature. See ./docker/cron for more options
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "opdata:/var/openproject/assets"
    command: "./docker/prod/worker"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    image: openproject/community:${TAG:-11}
    restart: unless-stopped
    environment:
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: 4
      RAILS_MAX_THREADS: 16
      USE_PUMA: "true"
      # set to true to enable the email receiving feature. See ./docker/cron for more options
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "opdata:/var/openproject/assets"
    command: "./docker/prod/cron"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    image: openproject/community:${TAG:-11}
    restart: unless-stopped
    environment:
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: 4
      RAILS_MAX_THREADS: 16
      USE_PUMA: "true"
      # set to true to enable the email receiving feature. See ./docker/cron for more options
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "opdata:/var/openproject/assets"
    command: "./docker/prod/seeder"
    restart: on-failure
    networks:
      - backend
